# Generated by Django 3.2.3 on 2021-06-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://s3.amazonaws.com/ODNUploads/5637b7e513fdbplaceholder_food_item_2.png', max_length=500),
        ),
    ]
